### ISSUE TITLE
Clarifications / Requests

### ISSUE THREAD

**Issue by jerryspan** [PythEsc/Research_project2#30]
Hi guys,

I am trying to get some fine details from the report/project in order to make some first steps towards some submission and I came up with the following questions/requests:

1) Which was the dataset used in the end for the report? Is it just Sainsbury/Tesco or the expanded list? That follows: The mongodb files contain which dataset(s)? It would be good if we were able to release/share the final version of the dataset we used.

2) Why for the experiments for preprocessing/no-preprocessing, exclusion of likes, MAE is measured, instead of MSE as well? Could I also have these figures in the excel? Just put them in dropbox.

Thanks for now, and I might come back if needed.

**Comment by Naxter** [comment]
Hey Jerry, 

1. We used the whole data from the database. And the database contains tesco/sainsburys + the additional crawled data. We kind of HAD to use this data in order to get the ~8000 posts with at least 1 reaction (other reaction than likes). So ye the mongo db files contain Tesco/Sainsburys + additional crawled data. 

2. Bruno should/could answer this for you I think because he ran the final tests. 

How is the grading going? :P we are excited.

**Comment by jerryspan** [comment]
* So, it's not Tescos/Sainsbury's anymore, but supermarket, that was confusing, because it is not mentioned once at the report.

* Waiting for Bruno then.

There might be some delays in the process because of group 2 problems, and Jean is responsible for announcing these but (and this is confidential :P) you should be looking at an 8. It could be an 8.5 if the report was slightly better. I hope you are happy with that.

**Comment by Naxter** [comment]
We stated that in the report actually, not sure about the report at the moment. Bruno will do this when he gets home from work. 

Oh okay, I see, thank you for the information. 8 is nice, better is always nicer of course...:-)

**Comment by jerryspan** [comment]
Yeah, I know. But DKE rules is that anything (project, thesis, internship) over 8.5 should be ready for publication at a *well-established* conference.

**Comment by Naxter** [comment]
So, one more week and we would have been better I think. Okay but no it is too late. :-D

**Comment by dnerger** [comment]
Since this is kinda public, would you mind dropping the grade for group 1 as well ;) @jerryspan

**Comment by jerryspan** [comment]
@dnerger you should be expecting a 7.

am available for further clarifications regarding grading, once you hear the official results.

p.s. these messages will be self-destructed in the end of the day.

**Comment by dnerger** [comment]
Thanks for the update :)

I supplied the rest of our group with the information as well, so if you want you can delete the comment

**Comment by brunolubascher** [comment]
Hi Jerry,
we measure both MSE and MAE, but those graphs were done during the second block. At that point, we did not know which one was better, so we just chose the MAE.
During the third block, we chose to use MSE because it gave more weight to predictions that were way off.

All the experiment data is in a file in the Dropbox folder. You can see all there.

**Comment by jerryspan** [comment]
Thanks! That's really useful. We can safely close this "issue" now.
